#!/bin/sh

rm /etc/config/freifunk

uci set freifunk.contact=public
uci set freifunk.contact.nickname=' '
uci set freifunk.contact.name=' '
uci set freifunk.contact.mail=' '
uci set freifunk.contact.phone=' '
uci set freifunk.contact.note=' '

uci set freifunk.community=public
uci set freifunk.community.name='berlin'
uci set freifunk.community.homepage='http://berlin.freifunk.net'

uci set freifunk.system=defaults
uci set freifunk.system.zonename='Europe/Berlin'
uci set freifunk.system.timezone='CET-1CES'

uci set freifunk.wifi_device=defaults
uci set freifunk.wifi_device.diversity='1'
uci set freifunk.wifi_device.disabled='0'
uci set freifunk.wifi_device.country='DE'

uci set freifunk.wifi_device_5=defaults
uci set freifunk.wifi_device_5.diversity='1'
uci set freifunk.wifi_device_5.disabled='0'
uci set freifunk.wifi_device_5.country='DE'

uci set freifunk.olsr_interface=defaults
uci set freifunk.olsr_interface.Ip4Broadcast='255.255.255.255'

uci commit freifunk
