#!/bin/sh

. /lib/functions/guard.sh
guard "openvpn"

uci delete openvpn.custom_config
uci delete openvpn.sample_server
uci delete openvpn.sample_client
uci set openvpn.ffvpn=openvpn
uci set openvpn.ffvpn.enabled=0
uci set openvpn.ffvpn.client=1
uci commit openvpn

uci set network.ffvpn=interface
uci set network.ffvpn.ifname=ffvpn
uci set network.ffvpn.proto=none
uci commit network
