#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

[ "$INTERFACE" = ffuplink ] || exit

config_load ffwizard
config_get sharenet settings sharenet
[ "$sharenet" = 1 ] || exit

config_load freifunk-policyrouting
config_get pr_enable pr enable
config_get fallback pr fallback
config_get strict pr strict
config_get zones pr zones
[ "$pr_enable" = 1 ] || exit

if [ "$ACTION" = ifup ]; then
  logger -t ff-userlog "ffuplink interface is up"
  logger -t ff-userlog "creating ffuplink ip-rules"
  ifaces=$(uci -q get firewall.zone_freifunk.network) 
  network_get_subnet uplink_net ffuplink
  eval $(/bin/ipcalc.sh $uplink_net)
  for iface in $ifaces; do
    network_get_physdev netdev $iface
    ip rule add prio 19989 to $NETWORK/$PREFIX iif $netdev prohibit
    ip rule add prio 19990 iif $netdev lookup ffuplink
  done
  logger -t ff-userlog "ffuplink-interface is setup"
fi

if [ "$ACTION" = ifdown ]; then
  logger -t ff-userlog "ffuplink interface going down"
  ip route flush table ffuplink
  while true; do
    ip rule show | grep "^19990:" || break
    ip rule del prio 19990
  done
  while true; do
    ip rule show | grep "^19989:" || break
    ip rule del prio 19989
  done
fi
