include $(TOPDIR)/rules.mk

LUCI_TITLE:=Freifunk Berlin freifunk default configuration
LUCI_DESCRIPTION:=Freifunk Berlin configuration files for freifunk

define Package/freifunk-berlin-dhcp-defaults/postinst
# noop
endef

include ../../freifunk-berlin-generic.mk

# call BuildPackage - is done via freifunk-berlin-generic.mk --> luci.mk
