#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

config_load ffwizard
local sharenet
config_get sharenet settings sharenet

[ "$sharenet" = 1 ] || exit

if [ "$INTERFACE" = ffuplink ]; then
  if [ "$ACTION" = ifup ]; then
    local gateway
    logger -t ff-userlog "ffuplink connection will be established"
    network_get_gateway gateway wan
    ip route add default via ${gateway} dev ffuplink table olsr-tunnel
    logger -t ff-userlog "ffuplink connection has been established"
  fi
  if [ "$ACTION" = ifdown ]; then
    logger -t ff-userlog "ffuplink connection went down"
  fi
fi

[ "$INTERFACE" = wan ] || exit

#config_load openvpn
#local uci_vpn_enabled
#config_get uci_vpn_enabled ffuplink enabled

if [ "$ACTION" = ifup ]; then
  logger -t ff-userlog "WAN interface is up"
  if [ "$sharenet" = 1 ]; then
    logger -t ff-vpn-hotplug "configuring ffuplink on WAN interface"
    # Make sure OpenVPN connects only through WAN: set "local" option with WAN IP
    local wanip
    network_get_ipaddr wanip "wan"
    ip link add ffuplink type veth peer name ffuplink_wan
    brctl addif br-wan ffuplink_wan
    ip link set up ffuplink_wan
    ifup ffuplink
    exit
  fi
fi

if [ "$ACTION" = ifdown ]; then
  logger -t ff-userlog "WAN interface went down"
  if [ "$sharenet" = 1 ]; then
    logger -t ff-uplink-hotplug "taking down interface ffuplink"
    ifdown ffuplink
    exit
  fi
fi

