#!/bin/sh

. /etc/functions.sh

#Enable/Disable auto-ipv6
if ! [ "$(uci get autoipv6.tunnel.enable)" == 1 ] ; then
        logger -t auto-ipv6 "If you have a Internet uplink then uci set  autoipv6.tunnel.enable=1"
        exit 0
fi

#Kernel Tunnel Modul?
if [ "a""$(lsmod | grep '^sit ')" == "a" ] ; then
        logger -t auto-ipv6 "Please install kmod-sit and kmod-iptunnel4"
        exit 0
fi
#IPutils?
if [ "a""$(lsmod | grep '^sit ')" == "a" ] ; then
        logger -t auto-ipv6 "Please install ip"
        exit 0
fi
# IFUP?
[ "$ACTION" = "ifup" ] || exit 0


#Internet Gateway?
local IP4_IFACE
IP4_IFACE="$(uci -p /var/state get network.$INTERFACE.gateway)"
if [ "$IP4_IFACE" == "" ] ; then
	logger -t auto-ipv6 "No Local IPv4 IFACE found"
	exit 0
fi

IP4_LOCAL="$(uci -p /var/state get network.$INTERFACE.ipaddr)"
if [ "$IP4_LOCAL" == "" ] ; then
	logger -t auto-ipv6 "No Local IPv4 found"
	exit 0
fi



olsrd_find_hna6() {
	local cfg="$1"
	local netaddr="$2"
	config_get Netaddr $cfg netaddr
	if [ "$Netaddr" == "$netaddr" ] ; then
		neta="$count $neta"
	fi
	count=$((count+1))
	return 0
}

olsrd_search_hna6() {
	local cfg="$1"
	local found="0"
	config_get Netaddr $cfg netaddr
	for i in $hna6s ; do
		if [ "$Netaddr" == "$i" ] ; then
			found="1"
		fi
	done
	if [ "$found" == "0" ] ; then
		neta="$count $neta"
	fi
	count=$((count+1))
	return 0
}

net_find_iface() {
        local cfg="$1"
        if [ "$cfg" == "$IP4_IFACE" ] ; then
        	return 0
        fi
        case $cfg in
        	loopback) return 0 ;;
        	gvpn) return 0 ;;
        esac
        interfaces="$interfaces ""$cfg"
        return 0
}
olsrd_find_plugin(){
	local cfg="$1"
	local plugin="$2"
	config_get library "$cfg" library
	case $library in
		$plugin*)
			plugin_find="1"
			return 0
		;;
	esac
	plugin_count=$((plugin_count+1))
	return 0
}

find_public_ip(){
	local ret
	ret="$(wget -q -O - http://checkip.dyndns.org/index.html | awk {'print $6'} | sed 's/<.*$//')"
	echo "$ret"
}

case $IP4_LOCAL in
	1.*) IP4_LOCAL="$(find_public_ip)" ;;
	10.*) IP4_LOCAL="$(find_public_ip)" ;;
	192.168.*) IP4_LOCAL="$(find_public_ip)" ;;
	172.17.*) IP4_LOCAL="$(find_public_ip)" ;;
esac

if [ "$IP4_LOCAL" == "" ] ; then
	logger -t auto-ipv6 "No Local Public IPv4 found"
	exit 0
fi

# warum ist die umask von hotplug.d so restricktiev?
umask 022
#

IP6_SUFIX=$(printf "2002:%02x%02x:%02x%02x" $(echo $IP4_LOCAL|sed 's/\./ /g'))
logger -t auto-ipv6 "Applying IPv6 Sufix $IP6_SUFIX"
ip -6 route flush dev tun6to4 2&>1 1>/dev/null
ip link set dev tun6to4 down 2&>1 1>/dev/null
ip tunnel del tun6to4 2&>1 1>/dev/null
ip tunnel add tun6to4 mode sit remote any local $IP4_LOCAL ttl 64
#ip tunnel add tun6to4 mode sit remote any local $(ip -4 r get 1|sed -n 's/.* src //p') ttl 64
ip link set dev tun6to4 up
ip addr add "$IP6_SUFIX""::1/16" dev tun6to4
ip route add "::192.88.99.1" dev tun6to4
ip route add "2000::/3" via "::192.88.99.1" dev tun6to4 metric 1
ip route add "::/0" via "::192.88.99.1" dev tun6to4 metric 1

config_load network
interfaces=""
config_foreach net_find_iface interface
restart_radvd=0
restart_olsrd=0
restart_crond=0
hna6s="::"
for i in $(echo $interfaces) ; do
	[ "$(uci get network.$i.proto)" == "static" ] || continue
	DEV=$(uci -p/var/state get network.$i.ifname)
	grep -q $DEV /proc/net/dev || {
		logger -t auto-ipv6 "Device Not Found IP6_SUFIX $IP6_SUFIX interfaces $i DEV $DEV check your uci config"
		continue
	}
	IP6_UCI=$(uci get network.$i.ip6addr)
	if [ $(echo $IP6_UCI | grep -i fdca) ] ; then
		uci set network.$i.ip6addr_fdca="$IP6_UCI"
		IP6_UCI=''
	fi
	IP6_OLDSUFIX="$(echo $IP6_UCI | cut -d ':' -f -3)"
	IP6_OLDUNIQ="$(echo $IP6_UCI | cut -d ':' -f 4)"
	[ -z $IP6_OLDSUFIX ] || {
		[ "$IP6_SUFIX" == "$IP6_OLDSUFIX" ] && ifconfig "$DEV" | grep -q -e "$IP6_SUFIX"".*1\/64" && {
			hna6s="$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::"" $hna6s"
			continue
		}
	}
	#uci set "network.$i.ip6oldsufix=$IP6_SUFIX"
	#Uniq 4Bybte from urandom
	IP6_UNIQ="$(head -n 1 /dev/urandom 2>/dev/null | md5sum | cut -b 1-4)"
	#uci set "network.$i.ip6olduniq=$IP6_UNIQ"
	#uci commit network
	[ -z $IP6_OLDSUFIX ] || {
		ifconfig "$DEV" del "$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::1/64"
	}
	for j in $(ifconfig $DEV | grep Scope:Global | cut -d ' ' -f 13 ) ; do
		ifconfig "$DEV" del "$j"
	done
	sysctl -w "net.ipv6.conf.$DEV.autoconf=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_redirects=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_ra=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_ra_defrtr=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_ra_pinfo=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_source_route=0"
	ifconfig "$DEV" add "$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
	uci -P /var/state set network.$i.ip6addr="$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
	uci set network.$i.ip6addr="$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
	uci commit network
	hna6s="$IP6_SUFIX"":""$IP6_UNIQ""::"" $hna6s"

	restart_radvd=1
done

if [ "6and4" == "$(uci get olsrd.@olsrd[0].IpVersion)" ] ; then
	config_load olsrd
	for i in $hna6s ; do
		local neta=""
		local count=0
		config_foreach olsrd_find_hna6 Hna6 $i
		if [ "$neta" == "" ] ; then
			uci add olsrd Hna6
			uci set "olsrd.@Hna6[-1].prefix=64"
			uci set "olsrd.@Hna6[-1].netaddr=""$i"
			uci commit olsrd
			restart_olsrd=1
		fi
	done

	local neta=""
	local count=0
	config_foreach olsrd_search_hna6 Hna6
	for i in $neta ; do
		uci delete "olsrd.@Hna6["$i"]"
		uci commit olsrd
		restart_olsrd=1
	done
fi


grep -q ping6 /etc/crontabs/root || {
	echo '* * * * *       ping6 -w 59 ipv6.google.com 1>/dev/null &' >> /etc/crontabs/root
	echo '* * * * *       ping6 -w 59 six.heise.de 1>/dev/null &' >> /etc/crontabs/root
	echo '* * * * *       ping6 -w 59 druschba.pberg.freifunk.net 1>/dev/null &' >> /etc/crontabs/root
	restart_crond=1
	}

if [ $restart_crond -eq 1 ] ; then
	if ! [ -z "$(pidof crond)" ] ; then
		/etc/init.d/crond stop
		killall -9 crond
		/etc/init.d/crond start
	fi
fi
if [ $restart_radvd -eq 1 ] ; then
	if ! [ -z "$(pidof radvd)" ] ; then
		/etc/init.d/radvd stop
		killall -9 radvd
		/etc/init.d/radvd start
	fi
fi
if [ $restart_olsrd -eq 1 ] ; then
	if ! [ -z "$(pidof olsrd)" ] ; then
		/etc/init.d/olsrd stop
		killall -9 olsrd
		/etc/init.d/olsrd start
	fi
fi

