#!/bin/sh


#Enable/Disable auto-ipv6
[ "$(uci get autoipv6.olsr_node.enable)" == 1 ] || exit 0

. /etc/functions.sh

olsrd_find_hna6() {
	local cfg="$1"
	local hna6="$2"
	config_get netaddr "$cfg" netaddr
	if [ "$netaddr" == "$hna6" ] ; then
		hna6_find="$hna6_count"
	fi
	hna6_count=$((hna6_count+1))
	return 0
}

net_find_iface() {
        local cfg="$1"
        case $cfg in
        	loopback) return 0 ;;
        	gvpn) return 0 ;;
        esac
        interfaces="$interfaces ""$cfg"
        return 0
}

IP6_SUFIX="$(wget -q -O - http://[::1]:2006/hna | grep '::/0' | cut -d "$(printf "\t")" -f 2 | cut -d ':' -f 1-3)"
[ -z $IP6_SUFIX ] && exit 0

config_load network
interfaces=""
config_foreach net_find_iface interface
for i in $(echo $interfaces) ; do
	#Interface
	DEV=$(uci -p/var/state get network.$i.ifname)
	#Sufix
	IP6_OLDSUFIX=$(uci -q -p/var/state get network.$i.ip6oldsufix)
	logger -t auto-ipv6 "interface: $i device: $DEV Check IPv6 New Sufix $IP6_SUFIX and Old Sufix $IP6_OLDSUFIX"
	[ "$IP6_SUFIX" == "$IP6_OLDSUFIX" ] && ifconfig "$DEV" | grep -q -e "$IP6_SUFIX"".*1\/64" && exit 0
	uci set "network.$i.ip6oldsufix=$IP6_SUFIX"
	#Uniq 4Bybte from urandom
	IP6_OLDUNIQ=$(uci -q -p/var/state get network.$i.ip6olduniq)
	IP6_UNIQ="$(head -n 1 /dev/urandom 2>/dev/null | md5sum | cut -b 1-4)"
	uci set "network.$i.ip6olduniq=$IP6_UNIQ"

	logger -t auto-ipv6 "Removing IPv6 Sufix ""$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::1/64"" from ""$DEV"
	#ip -6 addr del "$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::1/64" dev "$DEV" 2>/dev/null
	ifconfig "$DEV" del "$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::1/64"
	sysctl -w "net.ipv6.conf.$DEV.autoconf=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_redirects=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_ra=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_ra_defrtr=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_ra_pinfo=0"
	sysctl -w "net.ipv6.conf.$DEV.accept_source_route=0"
	for j in $(ifconfig $DEV | grep Scope:Global | cut -d ' ' -f 13 | grep -v fdca) ; do
		ifconfig "$DEV" del "$j"
	done
	logger -t auto-ipv6 "Applying IPv6 Sufix ""$IP6_SUFIX"":""$IP6_UNIQ""::1/64"" to ""$DEV"
	#ip -6 addr add "$IP6_SUFIX"":""$IP6_UNIQ""::1/64"       dev "$DEV" 2>/dev/null
	ifconfig "$DEV" add "$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
	uci -P /var/state set network.$i.ip6addr="$IP6_SUFIX"":""$IP6_UNIQ""::1/64"

	if [ -f /etc/config/olsrdv6 ] ; then
		config_load olsrdv6

		logger -t auto-ipv6 "Removing IPv6 Hna6 ""$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::"" from olsrd"
		hna6_count="0"
		hna6_find=""
		config_foreach olsrd_find_hna6 Hna6 "$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::"
		if [ "$hna6_find" == "" ] ; then
			logger -t auto-ipv6 "Applying IPv6 Hna6 ""$IP6_SUFIX"":""$IP6_UNIQ""::"" to olsrd"
			uci add olsrdv6 Hna6 >/dev/null
			uci set "olsrdv6.@Hna6[""$hna6_count""].prefix=64"
			uci set "olsrdv6.@Hna6[""$hna6_count""].netaddr=""$IP6_SUFIX"":""$IP6_UNIQ""::"
			uci commit
		else
			logger -t auto-ipv6 "Overwrite IPv6 Hna6 ""$IP6_SUFIX"":""$IP6_UNIQ""::"" to olsrd"
			uci set "olsrdv6.@Hna6[""$hna6_find""].prefix=64"
			uci set "olsrdv6.@Hna6[""$hna6_find""].netaddr=""$IP6_SUFIX"":""$IP6_UNIQ""::"
			uci commit
		fi
	fi
done


uci commit
if ! [ -z "$(pidof radvd)" ] ; then
	/etc/init.d/radvd stop
	killall -9 radvd
	/etc/init.d/radvd start
fi
if ! [ -z "$(pidof olsrd)" ] ; then
	/etc/init.d/olsrd stop
	killall -9 olsrd
	/etc/init.d/olsrd start
fi

