#!/bin/sh

resolve='0'
resolve_uci="$(uci -P /var/state get luci.general.resolve)"
if ping -q -c 3 api.flattr.com > /dev/null ; then
	resolve='1'
	if [ "$resolve_uci" != "$resolve" ] ; then
		sed -i '/.*luci\.general\.resolve.*/d' /var/state/luci
		uci -P /var/state set luci.general.resolve=1
		chmod 664 /var/state/luci
	fi
else
	resolve='0'
	if [ "$resolve_uci" != "$resolve" ] ; then
		sed -i '/.*luci\.general\.resolve.*/d' /var/state/luci
		uci -P /var/state set luci.general.resolve=0
		chmod 664 /var/state/luci
	fi
fi

resolve_n=0
resolve='1'
resolve_uci="$(uci -P /var/state get luci_olsr.general.resolve)"
remote_ip=""
remote_ip="$(wget -q -O - http://localhost:2006/links | cut -s -f 2)"
first=0
for i in $remote_ip ; do
	if [ $first -le 1 ] ; then
		first=$((first+1))
	else
		remote_host="$(grep ^$i /tmp/etc/hosts.olsr | cut -s -f 2)"
		if nslookup $remote_host >/dev/null 2&>1 ; then
			echo 111$i
			resolve_n=$((resolve_n+1))
		else
			resolve='0'
			if [ "$resolve_uci" != "$resolve" ] ; then
				sed -i '/.*luci_olsr\.general\.resolve.*/d' /var/state/luci_olsr
				uci -P /var/state set luci_olsr.general.resolve=0
				chmod 664 /var/state/luci_olsr
			fi
		fi
	fi
done

if [ "$resolve" == "1" -a $resolve_n -ge 1  -a "$resolve_uci" != "$resolve" ] ; then
	sed -i '/.*luci_olsr\.general\.resolve.*/d' /var/state/luci_olsr
	uci -P /var/state set luci_olsr.general.resolve=1
	chmod 664 /var/state/luci_olsr
fi

