include $(TOPDIR)/rules.mk

PKG_RELEASE:=3

LUCI_TITLE:=Freifunk Berlin guard function
LUCI_DESCRIPTION:=Freifunk Berlin guard function

define Package/freifunk-berlin-lib-guard/postinst
# noop
endef

include ../../freifunk-berlin-generic.mk

# call BuildPackage - is done via freifunk-berlin-generic.mk --> luci.mk
