#!/bin/sh

. /lib/functions/system.sh

# always set correct masquerading, regardless of guard
uci set firewall.zone_ffuplink.masq=1
uci commit firewall

uci -q get ffberlin-uplink || echo "" | uci import ffberlin-uplink
uci >/dev/null -q get ffberlin-uplink.preset || uci set ffberlin-uplink.preset=settings
uci >/dev/null -q get ffberlin-uplink.preset.current || uci set ffberlin-uplink.preset.current="tunnelberlin_tunneldigger"
if [[ $(uci get ffberlin-uplink.preset.current) != '"tunnelberlin_tunneldigger"' ]]; then
  uci rename ffberlin-uplink.preset.current=previous
  uci set ffberlin-uplink.preset.current="tunnelberlin_tunneldigger"
fi
uci commit ffberlin-uplink

. /lib/functions/guard.sh
guard "tunnelberlin_tunneldigger"

uci delete network.ffuplink_dev
uci set network.ffuplink_dev=device
uci set network.ffuplink_dev.name=ffuplink
# Create a static macaddr starting with "fe" for ffuplink devices
# See the website https://www.itwissen.info/MAC-Adresse-MAC-address.html
macaddr="fe"
for byte in 2 3 4 5 6; do
  macaddr=$macaddr`dd if=/dev/urandom bs=1 count=1 2> /dev/null | hexdump -e '1/1 ":%02x"'`
done
uci set network.ffuplink_dev.macaddr=$macaddr

uci delete network.ffuplink
uci set network.ffuplink=interface
uci set network.ffuplink.ifname=ffuplink
uci set network.ffuplink.proto=dhcp
# Put the resulting routing information from the dhcp request in the ffuplink table
# instead of the default table.  This prevents the dhcp request for the ffuplink
# interface from overwriting the routing table entries needed by br_wan.
uci set network.ffuplink.ip4table=ffuplink
uci set network.ffuplink.ip6table=ffuplink
uci commit network

# tunneldigger setup
UUID=$(uci -q get tunneldigger.ffuplink.uuid)
if [ $? -eq 1 ]; then
  UUID=$macaddr
  for byte in 7 8 9 10; do
    UUID=$UUID`dd if=/dev/urandom bs=1 count=1 2> /dev/null | hexdump -e '1/1 ":%02x"'`
  done
fi

uci delete tunneldigger.ffuplink
uci set tunneldigger.ffuplink=broker
uci -q delete tunneldigger.ffuplink.address
for srv in a b c d e f; do
  uci add_list tunneldigger.ffuplink.address=$srv.tunnel.berlin.freifunk.net:8942
done
uci set tunneldigger.ffuplink.uuid=$UUID
uci set tunneldigger.ffuplink.interface=ffuplink
uci set tunneldigger.ffuplink.broker_selection=usage
uci set tunneldigger.ffuplink.bind_interface=wan
uci set tunneldigger.ffuplink.enabled=1
uci commit tunneldigger

