#!/bin/sh

. /lib/functions/guard.sh
guard "openvpn"

uci delete openvpn.custom_config
uci delete openvpn.sample_server
uci delete openvpn.sample_client
uci commit openvpn

uci set network.ffuplink=interface
uci set network.ffuplink.ifname=ffuplink
uci set network.ffuplink.proto=none
uci commit network
