#!/bin/sh

# set set auth-type required for this uplink-type, e.g. for freifunk-wizard
uci set ffberlin-uplink.uplink.auth=x509
uci commit ffberlin-uplink.uplink

uci -q delete openvpn.custom_config
uci -q delete openvpn.sample_server
uci -q delete openvpn.sample_client
uci set openvpn.ffuplink=openvpn
uci set openvpn.ffuplink.client=1
uci set openvpn.ffuplink.dev=ffuplink
uci set openvpn.ffuplink.status="/var/log/openvpn-status-ffuplink.log"
uci set openvpn.ffuplink.up="/lib/freifunk/ffvpn-up.sh"
uci set openvpn.ffuplink.route_nopull=1
uci commit openvpn

# reconfigure ffuplink interface
uci -q delete network.ffuplink_dev
uci -q delete network.ffuplink
uci set network.ffuplink=interface
uci set network.ffuplink.ifname=ffuplink
uci set network.ffuplink.proto=none
uci commit network
