#!/bin/sh

. /lib/functions/guard.sh
guard "ipsec"

uci set network.ffvpn=interface
uci set network.ffvpn.ifname=ffvpn
uci set network.ffvpn.proto=none
uci commit network

# add routing tables
# see also freifunk-berlin-olsrd-defaults
tables="/etc/iproute2/rt_tables"
test -d /etc/iproute2/ || mkdir -p /etc/iproute2/
grep -q "200 ff-client" $tables || echo "200 ff-client" >> $tables
