#!/bin/sh /etc/rc.common
# Copyright (C) 2012 Patrick Grimm

START=55
SERVER="ws-mirror-server"
SERVER_BIN="/usr/sbin/ws-mirror-server"
SERVER_ARGS="-r linknx -x linknxws -p 7682"
SERVER_PID="ws-mirror-server-linknx"

start() {
	start-stop-daemon -S -x $SERVER_BIN \
		-p /var/run/${SERVER_PID}.pid \
		-m -b -- ${SERVER_ARGS}
}

stop() {
	[ -f /var/run/${SERVER_PID}.pid ] && {
		start-stop-daemon -K -q -n ${SERVER_BIN##*/} \
			-p /var/run/${SERVER_PID}.pid -s TERM

		rm -f /var/run/${SERVER_PID}.pid
	}
}
