#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	#( . /etc/uci-defaults/ws-mirror-server ) &&	rm -f /etc/uci-defaults/ws-mirror-server
	/etc/init.d/ws-mirror-server enable
	/etc/init.d/ws-mirror-server start
}

