#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

config_load ffwizard
local sharenet
config_get sharenet settings sharenet

[ "$sharenet" = 1 ] || exit

if [ "$INTERFACE" = ffuplink ]; then
  if [ "$ACTION" = ifup ]; then
#
# The routing table assignment for ffuplink is set in 
# /etc/config/network with the ip{4|6}table options.
#
    logger -t ff-userlog "ffuplink connection has been established"
  fi
  if [ "$ACTION" = ifdown ]; then
    logger -t ff-userlog "ffuplink connection went down"
  fi
fi

[ "$INTERFACE" = wan ] || exit

if [ "$ACTION" = ifup ]; then
  logger -t ff-userlog "WAN interface is up"
  if [ "$sharenet" = 1 ]; then
    logger -t ff-userlog "configuring ffuplink on WAN interface"
    ifup ffuplink
    exit
  fi
fi

if [ "$ACTION" = ifdown ]; then
  logger -t ff-userlog "WAN interface went down"
  if [ "$sharenet" = 1 ]; then
    logger -t ff-uplink-hotplug "taking down interface ffuplink"
    ifdown ffuplink
    exit
  fi
fi
