#!/bin/sh

THIS_UPLINKNAME="vpn03_openvpn"

. /lib/functions/guard.sh

# always set correct masquerading, regardless of guard
uci set firewall.zone_ffuplink.masq=0
uci commit firewall

current_preset=$(uci get ffberlin-uplink.preset.current)
if [ ${current_preset} != ${THIS_UPLINKNAME} ]; then
  # do not track preset when it was 'undefined', aka never configured
  if [ ${current_preset} != "undefined" ]; then
    logger -t "ffuplink" "uplink-preset has been changed."
    uci set ffberlin-uplink.preset.previous=${current_preset}
  fi
  uci set ffberlin-uplink.preset.current=${THIS_UPLINKNAME}
  # call uci-default of package freifunk-berlin-openvpn-files again to recreate initial config
  sh /rom/etc/uci-defaults/freifunk-berlin-z90_openvpn
fi
uci commit ffberlin-uplink

# This sets up this uplinks individual parameters
guard "vpn03_openvpn"

uci set openvpn.ffuplink.proto=udp4
uci set openvpn.ffuplink.dev_type=tun
uci set openvpn.ffuplink.persist_key=1
uci set openvpn.ffuplink.keepalive="10 60"
uci set openvpn.ffuplink.ns_cert_type=server
uci set openvpn.ffuplink.comp_lzo="no"
uci set openvpn.ffuplink.script_security=2
uci set openvpn.ffuplink.cipher="none"
uci set openvpn.ffuplink.mssfix=1300
uci add_list openvpn.ffuplink.remote="vpn03.berlin.freifunk.net 1194"
uci add_list openvpn.ffuplink.remote="vpn03-backup.berlin.freifunk.net 1194"
uci set openvpn.ffuplink.ca="/etc/openvpn/freifunk-ca.crt"
uci set openvpn.ffuplink.cert="/etc/openvpn/ffuplink.crt"
uci set openvpn.ffuplink.key="/etc/openvpn/ffuplink.key"
uci commit openvpn.ffuplink

uci set network.ffuplink.disabled=0
uci commit network.ffuplink
