include $(TOPDIR)/rules.mk

LUCI_TITLE:=Freifunk Berlin uhttpd default configuration
LUCI_DEPENDS:=+uhttpd +freifunk-berlin-lib-guard
LUCI_DESCRIPTION:=Freifunk Berlin configuration files for uhttpd

define Package/freifunk-berlin-uhttpd-defaults/postinst
# noop
endef

include ../../freifunk-berlin-generic.mk

# call BuildPackage - is done via freifunk-berlin-generic.mk --> luci.mk
