#!/bin/sh

# check if defaults have already been set
CFG="default"
CFG_FILE="/etc/config/$CFG"
SECTION="packages"
NAME="default"
OPTION="dhcp"

[ ! -f $CFG_FILE ] && touch $CFG_FILE && uci set $CFG.$NAME=$SECTION
[ "$(uci get $CFG.$NAME.$OPTION)" == "1" ] && return 0
uci set $CFG.$NAME.$OPTION=1

# add dns entry frei.funk
uci set dhcp.frei_funk=domain
uci set dhcp.frei_funk.name=frei.funk
uci set dhcp.frei_funk.ip=192.168.42.1

uci commit dhcp
