#!/bin/sh

. /lib/functions/guard.sh
guard "dhcp"


# add dns entry frei.funk
uci set dhcp.frei_funk=domain
uci set dhcp.frei_funk.name=frei.funk
uci set dhcp.frei_funk.ip=192.168.42.1

# add dns entry frei.funk for ipv6
router_ula=$(uci get network.globals.ula_prefix | sed -e 's/\/48/1/')
uci set dhcp.frei_funk_ipv6=domain
uci set dhcp.frei_funk_ipv6.name=frei.funk
uci set dhcp.frei_funk_ipv6.ip=$router_ula

uci commit dhcp
