#!/bin/sh

# always set correct masquerading, regardless of guard
uci set firewall.zone_ffuplink.masq=1
uci commit firewall

uci -q get ffberlin-uplink || echo "" | uci import ffberlin-uplink
uci >/dev/null -q get ffberlin-uplink.preset || uci set ffberlin-uplink.preset=settings
uci >/dev/null -q get ffberlin-uplink.preset.current || uci set ffberlin-uplink.preset.current="tunnelberlin_openvpn"
if [[ $(uci get ffberlin-uplink.preset.current) != '"tunnelberlin_openvpn"' ]]; then
  uci rename ffberlin-uplink.preset.current=previous
  uci set ffberlin-uplink.preset.current="tunnelberlin_openvpn"
fi
uci commit ffberlin-uplink

. /lib/functions/guard.sh
guard "tunnelberlin_openvpn"

uci set openvpn.ffuplink=openvpn
uci set openvpn.ffuplink.enabled=0
uci set openvpn.ffuplink.client=1
uci set openvpn.ffuplink.proto=udp4
uci set openvpn.ffuplink.dev=ffuplink
uci set openvpn.ffuplink.dev_type=tun
uci set openvpn.ffuplink.persist_key=1
uci set openvpn.ffuplink.keepalive="10 60"
uci set openvpn.ffuplink.remote_cert_tls=server
uci set openvpn.ffuplink.compress="lzo"
uci set openvpn.ffuplink.script_security=2
uci set openvpn.ffuplink.cipher="none"
uci set openvpn.ffuplink.mssfix=1300
uci add_list openvpn.ffuplink.remote="tunnel-gw.berlin.freifunk.net 1194"
uci set openvpn.ffuplink.ca="/etc/openvpn/tunnel-berlin-ca.crt"
uci set openvpn.ffuplink.extra_certs="/etc/openvpn/tunnel-berlin-extra.crt"
uci set openvpn.ffuplink.cert="/etc/openvpn/ffuplink.crt"
uci set openvpn.ffuplink.key="/etc/openvpn/ffuplink.key"
uci set openvpn.ffuplink.status="/var/log/openvpn-status-ffuplink.log"
uci set openvpn.ffuplink.up="/lib/freifunk/ffvpn-up.sh"
uci set openvpn.ffuplink.route_nopull=1
uci commit openvpn
