#!/bin/sh
echo "Content-type: text/plain"
echo ""
USER=root
# taken from http://serverfault.com/a/240961
grep ${USER} /etc/shadow | awk -F":" '{ if ($2 == "!" || $2 == "") \
		printf "password_is_set:no";\
	else \
		printf "password_is_set:yes"\
	}'
