include $(TOPDIR)/rules.mk

LUCI_TITLE:=Freifunk Berlin system default configuration
LUCI_DEPENDS:=+freifunk-berlin-lib-guard
LUCI_DESCRIPTION:=Freifunk Berlin configuration files for basic system-files

include ../../freifunk-berlin-generic.mk

# call BuildPackage - is done via freifunk-berlin-generic.mk --> luci.mk
