#!/bin/sh

set_default_config()
{
	local cfg="$1"
	config_get type "$cfg" "type"
	config_get hwmode "$cfg" "hwmode"
	case $type in
		mac80211)
			uci set freifunk.wifi_device.hwmode=$hwmode
			uci set freifunk.wifi_device.channel=1
			uci set freifunk.wifi_device.diversity=""
			uci set freifunk.wifi_device.disabled=0
			uci set freifunk.wifi_device.txpower="15"
			uci set freifunk.wifi_device.country=DE
			uci set freifunk.wifi_device.distance=1000
			uci set freifunk.wifi_iface=defaults
			uci set freifunk.wifi_iface.mode=adhoc
			uci set freifunk.wifi_iface.bssid="02:CA:FF:EE:BA:BE"
			uci set freifunk.wifi_iface.sw_merge=""
			uci set freifunk.wifi_iface.noscan=1
			uci commit freifunk
		;;
	esac
}

[ "$(uci -q get freifunk.wizard)" == "settings" ] || uci set freifunk.wizard=settings
uci set freifunk.interface.dns="2002:d596:2a92:1:71:53:: 2002:5968:c28e::53 88.198.178.18 141.54.1.1 212.204.49.83 8.8.8.8 8.8.4.4"
uci commit freifunk
uci set uhttpd.main.rfc1918_filter=0
uci commit uhttpd
uci set luci_olsr.general.resolve=0
uci commit luci_olsr
uci set luci.general=internal
uci set luci.general.resolve=0
uci commit luci

grep -q 'ff_luci_resolve' /etc/crontabs/root || echo '*/5 * * * *     /usr/sbin/ff_luci_resolve' >> /etc/crontabs/root

(
while true ; do
	sleep 30
	wifie=0
	config_load wireless && wifie=1
	if [ $wifie -eq 1 ] ; then
		config_foreach set_default_config wifi-device
		exit 0
	fi
done
) >/dev/null &

