#!/bin/sh

uci batch <<EOF
	set freifunk.pberg='community'
        set freifunk.pberg.name='Freifunk Berlin Prenzlauer Berg'
        set freifunk.pberg.homepage='http://pberg.freifunk.net'
        set freifunk.pberg.ssid='olsr.freifunk.net'
        set freifunk.pberg.mesh_network='104.0.0.0/8'
        set freifunk.pberg.splash_network='10.104.0.0/16'
        set freifunk.pberg.splash_prefix='27'
        set freifunk.pberg.external='freifunk_berlin'
EOF
uci commit freifunk
