#!/bin/sh

#change default ip to avoid collision with uses's local network
uci set network.lan.ipaddr=192.168.42.1
uci commit network

#set dns name frei.funk
uci set dhcp.frei_funk=domain
uci set dhcp.frei_funk.name=frei.funk
uci set dhcp.frei_funk.ip=192.168.42.1
uci commit dhcp

#configure olsr jsoninfo plugin
PLUGIN="$(uci add olsrd LoadPlugin)"
uci set olsrd.$PLUGIN.accept=0.0.0.0
uci set olsrd.$PLUGIN.library=olsrd_jsoninfo.so.0.0
uci set olsrd.$PLUGIN.ignore=0

PLUGIN="$(uci add olsrd6 LoadPlugin)"
uci set olsrd6.$PLUGIN.accept=::
uci set olsrd6.$PLUGIN.library=olsrd_jsoninfo.so.0.0
uci set olsrd6.$PLUGIN.ignore=0

#configure olsr watchdog plugin
PLUGIN="$(uci add olsrd LoadPlugin)"
uci set olsrd.$PLUGIN.library=olsrd_watchdog.so.0.1
uci set olsrd.$PLUGIN.file=/var/run/olsrd.watchdog
uci set olsrd.$PLUGIN.interval=30

PLUGIN="$(uci add olsrd6 LoadPlugin)"
uci set olsrd6.$PLUGIN.library=olsrd_watchdog.so.0.1
uci set olsrd6.$PLUGIN.file=/var/run/olsrd.watchdog
uci set olsrd6.$PLUGIN.interval=30

#configure olsr nameservice plugin
# it's already available in olsrd config file
COUNTER=0
LIBRARY="$(uci get olsrd.@LoadPlugin[$COUNTER].library)"
while [[ $LIBRARY != "" ]]
do
        if [ $LIBRARY == "olsrd_nameservice.so.0.3" ]
        then
                uci set olsrd.@LoadPlugin[$COUNTER].suffix=.olsr
                uci set olsrd.@LoadPlugin[$COUNTER].hosts_file=/tmp/hosts/olsr
                uci set olsrd.@LoadPlugin[$COUNTER].latlon_file=/var/run/latlon.js
                uci set olsrd.@LoadPlugin[$COUNTER].services_file=/var/etc/services.olsr
                uci commit olsrd
        fi
	COUNTER=$(($COUNTER + 1))
	LIBRARY="$(uci get olsrd.@LoadPlugin[$COUNTER].library)"
done

#it's not available in olsrd6 config file > create a new section
PLUGIN="$(uci add olsrd6 LoadPlugin)"
uci set olsrd6.$PLUGIN.library=olsrd_nameservice.so.0.3
uci set olsrd6.$PLUGIN.suffix=.olsr
uci set olsrd6.$PLUGIN.hosts_file=/tmp/hosts/olsr
uci set olsrd6.$PLUGIN.latlon_file=/var/run/latlon.js.ipv6
uci set olsrd6.$PLUGIN.services_file=/var/etc/services.olsr.ipv6

uci commit olsrd
uci commit olsrd6

