#!/bin/sh

#change default ip to avoid collision with uses's local network
uci set network.lan.ipaddr=192.168.42.1
uci commit network

#set dns name frei.funk
DOMAIN="$(uci add dhcp domain)"
uci set dhcp.$DOMAIN.name=frei.funk
uci set dhcp.$DOMAIN.ip=192.168.42.1
uci commit dhcp

#configure olsr jsoninfo plugin
PLUGIN="$(uci add olsrd LoadPlugin)"
uci set olsrd.$PLUGIN.accept=0.0.0.0
uci set olsrd.$PLUGIN.library=olsrd_jsoninfo.so.0.0
uci set olsrd.$PLUGIN.ignore=0

PLUGIN="$(uci add olsrd6 LoadPlugin)"
uci set olsrd.$PLUGIN.accept=::
uci set olsrd.$PLUGIN.library=olsrd_jsoninfo.so.0.0
uci set olsrd.$PLUGIN.ignore=0
