#!/bin/sh
SEED="$( dd if=/dev/urandom bs=2 count=1 2>&- | hexdump | if read line; then echo 0x${line#* }; fi )"
MIN="$(( $SEED % 59 ))"
echo >/usr/lib/micron.d/owm "$MIN * * * *	test -e /usr/sbin/owm.lua && /usr/sbin/owm.lua"
