include $(TOPDIR)/rules.mk

LUCI_TITLE:=Freifunk Berlin dhcp default configuration
LUCI_DEPENDS:=+dnsmasq +freifunk-berlin-lib-guard
LUCI_DESCRIPTION:=Freifunk Berlin configuration files for dhcp

include ../../freifunk-berlin-generic.mk

# call BuildPackage - is done via freifunk-berlin-generic.mk --> luci.mk
