#!/bin/sh

. /lib/functions/guard.sh
guard "vpn03-ipsec"

# add routing tables
# see also freifunk-berlin-olsrd-defaults
tables="/etc/iproute2/rt_tables"
test -d /etc/iproute2/ || mkdir -p /etc/iproute2/
grep -q "200 ff-client" $tables || echo "200 ff-client" >> $tables

uci set network.ffvpn=interface
uci set network.ffvpn.ifname=ffvpn
uci set network.ffvpn.proto=none

# add basic ip rules
# send all traffic from iface "dhcp" via VPN
uci set network.default_dhcp_ipv4=rule
uci set network.default_dhcp_ipv4.in=dhcp
uci set network.default_dhcp_ipv4.priority=20000
uci set network.default_dhcp_ipv4.lookup=ff-client
# other traffic from iface "dhcp" gets unreachable
uci set network.default_unreachable_dhcp_ipv4=rule
uci set network.default_unreachable_dhcp_ipv4.in=dhcp
uci set network.default_unreachable_dhcp_ipv4.priority=20001
uci set network.default_unreachable_dhcp_ipv4.action=unreachable

uci commit network
