#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-app-linknx ) &&	rm -f /etc/uci-defaults/luci-app-linknx
	rm -f /tmp/luci-indexcache
	/etc/init.d/ws-mirror-server-linknx enable
	/etc/init.d/ws-mirror-server-linknx start
	/etc/init.d/ubus-linknx enable
	/etc/init.d/ubus-linknx start
}

