#!/bin/sh

# always set correct masquerading, regardless of guard
uci set firewall.zone_ffuplink.masq=1
uci commit firewall

uci delete network.ffuplink_dev
uci set network.ffuplink_dev=device
uci set network.ffuplink_dev.type=veth
uci set network.ffuplink_dev.name=ffuplink
uci set network.ffuplink_dev.peer_name=ffuplink_wan
# add ffuplink_dev to br-wan
uci set network.wan.ifname="$(uci get network.wan.ifname) ffuplink_wan"
uci commit network

. /lib/functions/guard.sh
guard "notunnel"

uci delete network.ffuplink
uci set network.ffuplink=interface
uci set network.ffuplink.ifname=ffuplink
uci set network.ffuplink.proto=dhcp
# Put the resulting routing information from the dhcp request in the ffuplink table
# instead of the default table.  This prevents the dhcp request for the ffuplink
# interface from overwriting the routing table entries needed by br_wan.
uci set network.ffuplink.ip4table=ffuplink
uci set network.ffuplink.ip6table=ffuplink
uci commit network
