#!/bin/sh

THIS_UPLINKNAME="notunnel"

. /lib/functions/freifunk-berlin-network.sh 
. /lib/functions/guard.sh
. /lib/functions.sh

# always set correct masquerading, regardless of guard
uci set firewall.zone_ffuplink.masq=1
uci commit firewall

current_preset=$(uci get ffberlin-uplink.preset.current)
if [ ${current_preset} != ${THIS_UPLINKNAME} ]; then
  # do not track preset when it was 'undefined', aka never configured
  if [ ${current_preset} != "undefined" ]; then
    logger -t "ffuplink" "uplink-preset has been changed."
    uci set ffberlin-uplink.preset.previous=${current_preset}
    create_ffuplink
  fi
  uci set ffberlin-uplink.preset.current=${THIS_UPLINKNAME}
fi
# set set auth-type required for this uplink-type, e.g. for freifunk-wizard
uci set ffberlin-uplink.uplink.auth=none
uci commit ffberlin-uplink

guard "notunnel"

uci -q delete network.ffuplink_dev
uci set network.ffuplink_dev=device
uci set network.ffuplink_dev.type=veth
uci set network.ffuplink_dev.name=ffuplink
uci set network.ffuplink_dev.peer_name=ffuplink_wan
# Create a static macaddr starting with "fe" for ffuplink devices
# See the website https://www.itwissen.info/MAC-Adresse-MAC-address.html
macaddr="fe"
for byte in 2 3 4 5 6; do
  macaddr=$macaddr`dd if=/dev/urandom bs=1 count=1 2> /dev/null | hexdump -e '1/1 ":%02x"'`
done
uci set network.ffuplink_dev.macaddr=$macaddr
uci commit network.ffuplink_dev

# add ffuplink_dev to br-wan if not there
ifnames=$(uci get network.wan.ifname)
list_contains ifnames ffuplink_wan || uci set network.wan.ifname="${ifnames} ffuplink_wan"
uci commit network.wan

uci set network.ffuplink.proto=dhcp
uci set network.ffuplink.disabled=0
uci commit network.ffuplink
