#!/bin/sh

# check if defaults have already been set
CFG="default"
CFG_FILE="/etc/config/$CFG"
SECTION="packages"
NAME="default"
OPTION="network"

[ ! -f $CFG_FILE ] && touch $CFG_FILE && uci set $CFG.$NAME=$SECTION
[ "$(uci get $CFG.$NAME.$OPTION)" == "1" ] && return 0
uci set $CFG.$NAME.$OPTION=1

# change default ip to avoid collision with user's local network
uci set network.lan.ipaddr=192.168.42.1

# do not use dns servers provided by dhcp - we maintain a static list of 
# dns servers instead
uci set network.wan.peerdns=0
uci set network.wan6.peerdns=0

# add tunl0 interface - tunl0 is the ipip tunnel interface for the olsr
# SmartGateway plugin
uci set network.tunl0=interface
uci set network.tunl0.ifname=tunl0
uci set network.tunl0.proto=none

uci commit network
