#!/bin/sh
# This file is for l2gvpn startup
# usage: ./up_down up bbb gvpn

table=111

up_bbb()
{
    #vpn-bbb1
    #ip link set dev $INTERFACE up
    #ip addr add dev $INTERFACE 77.87.48.81/26 broadcast 77.87.48.127

    #insert routing stuff
    ip ro add default table $table via 77.87.48.247 dev tun0
    ip ro add throw 104.0.0.0/8 table $table
    ip ro add throw 77.87.48.0/21 table $table
    ip rule add iif $1 to 104.0.0.0/8 lookup $table prio 100
    ip rule add iif $1 to 77.87.48.0/21 lookup $table prio 100
    ip rule add iif $1 to 194.26.180.0/24 lookup $table prio 100
    ip rule add iif tun0 to 104.0.0.0/8 lookup $table prio 100
    ip rule add iif tun0 to 77.87.48.0/21 lookup $table prio 100
    ip rule add iif tun0 to 194.26.180.0/24 lookup $table prio 100
    ip rule add iif lo to 104.0.0.0/8 lookup $table prio 100
    ip rule add iif lo to 77.87.48.0/21 lookup $table prio 100
    ip rule add iif lo to 194.26.180.0/24 lookup $table prio 100
    ip rule add from 77.87.48.81 lookup $table prio 100
    ip rule add from 77.87.48.246 lookup $table prio 100
}

down_bbb()
{
    # This file closes down the tap device.

    #ifconfig $INTERFACE down
    #ifconfig $INTERFACE:bat down

    #flush routing stuff
    #ip ru del from <deine IP> lookup 100
    ip ro flush table $table
    ip rule del iif $1 to 104.0.0.0/8 lookup $table prio 100
    ip rule del iif $1 to 77.87.48.0/21 lookup $table prio 100
    ip rule del iif $1 to 194.26.180.0/24 lookup $table prio 100
    ip rule del iif tun0 to 104.0.0.0/8 lookup $table prio 100
    ip rule del iif tun0 to 77.87.48.0/21 lookup $table prio 100
    ip rule del iif tun0 to 194.26.180.0/24 lookup $table prio 100
    ip rule del iif lo to 104.0.0.0/8 lookup $table prio 100
    ip rule del iif lo to 77.87.48.0/21 lookup $table prio 100
    ip rule del iif lo to 194.26.180.0/24 lookup $table prio 100
    ip rule del from 77.87.48.81 lookup $table prio 100
    ip rule del from 77.87.48.246 lookup $table prio 100
}


eval updown=$1
eval netname=$2
eval devname=$3

#(
logger "updown: $updown netname: $netname devname: $devname"
"$updown"_"$netname" $devname 
# 1>/dev/null 2>/dev/null &
#)
