#!/bin/sh

uci set network.ffuplink.ffberlin_uplinktype=direct

. /lib/functions/guard.sh
guard "notunnel"

uci delete network.ffuplink
uci set network.ffuplink=interface
uci set network.ffuplink.ifname=ffuplink
uci set network.ffuplink.proto=dhcp
uci commit network
