#!/bin/sh
# Copyright (C) 2016 OpenWrt.org

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

case "$1" in
	list)
		json_init

		json_add_object "apply"
		json_add_object "config"
		json_close_object
		json_close_object

		json_dump
	;;
	call)
		case "$2" in
			apply)
				local json
				local tmpfile

				# parse
				read json

				if [ $(jsonfilter -s "${json}" -t '@.config') != "object" ] ; then
					echo '{ "status": "failed", "description": "config does not exists or is not type object"}'
					exit 0
				fi

				# extract "config" value and save this in tmpfile
				config=$(jsonfilter -s "${json}" -e '@.config')
				tmpfile=$(mktemp /tmp/ffwizard_XXXXXX)
				echo $config > $tmpfile

				# run wizard script with config file
				FFWIZARD=$(ffwizard_apply -u $tmpfile)
				RET=$?
				if [ $RET -ne 0 ] ; then
					echo "{ \"status\": \"failed\", \"description\": \"ffwizard failed (return code $RET, error message: $FFWIZARD)\"}"
					exit 0
				fi
				echo '{ "status": "success", "description": "config has been applied" }'

				echo $config > /etc/ffwizard.config.json

				reboot
			;;
		esac
	;;
esac
