#!/bin/sh

. /lib/functions/guard.sh
guard "ffberlin_uplink"

# create ffberlin-uplink file an fill with basic settings
uci import ffberlin-uplink <<EOF
EOF

uci set ffberlin-uplink.preset=settings
uci set ffberlin-uplink.preset.current="undefined"
uci set ffberlin-uplink.uplink=settings
uci set ffberlin-uplink.uplink.auth=none
uci commit ffberlin-uplink

# create a very basic ffuplink interface
uci set network.ffuplink=interface
uci set network.ffuplink.ifname=ffuplink
# see https://github.com/freifunk-berlin/firmware/issues/561
uci set network.ffuplink.ip4table=ffuplink
uci set network.ffuplink.ip6table=ffuplink
# the following options need to be set by the individual uplink-package
uci set network.ffuplink.proto=none
uci commit network.ffuplink
